name: TestSuite
on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: '0'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm cache clean --force
      - run: npm install
      - run: npm i node-fetch
      - run: npm run build --if-present
      - run: npm i mochawesome
      - run: npm run cypress:run --headed --browser chrome --spec "cypress/integration/tests"
      - run: npm run jira-api-post
        env:
          CI: true