name: ActionLog
on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

  # Checkout Repo
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: '0'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  # Execute Test Suite
      - id: run_test
        run: |
          npm run test