name: TestSuite
  on: [push]
  branches: dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm cache clean --force
      - run: npm install
      - run: npm i node-fetch
      - run: npm run build --if-present
      - run: npm run cypress:run --spec "cypress/integration/tests"
      - run: npm run jira-api-post
        env:
          CI: true